"""
Constants and mappings used throughout the application.
"""

# Branch code to full name mapping
BRANCH_MAP = {
    'CSE': 'COMPUTER SCIENCE AND ENGINEERING',
    'CSM': 'COMPUTER SCIENCE AND ENGINEERING (ARTIFICIAL INTELLIGENCE AND MACHINE LEARNING)',
    'CSD': 'COMPUTER SCIENCE AND ENGINEERING (DATA SCIENCE)',
    'ECE': 'ELECTRONICS AND COMMUNICATION ENGINEERING',
    'EEE': 'ELECTRICAL AND ELECTRONICS ENGINEERING',
    'CIV': 'CIVIL ENGINEERING',
    'MEC': 'MECHANICAL ENGINEERING',
    'INF': 'INFORMATION TECHNOLOGY',
    'AID': 'ARTIFICIAL INTELLIGENCE AND DATA SCIENCE',
    'CSO': 'COMPUTER SCIENCE AND ENGINEERING (IOT)',
    'CSC': 'COMPUTER SCIENCE AND ENGINEERING (CYBER SECURITY)',
    'CSB': 'COMPUTER SCIENCE AND BUSINESS SYSTEM',
    'CSW': 'COMPUTER ENGINEERING (SOFTWARE ENGINEERING)',
    'EIE': 'ELECTRONICS AND INSTRUMENTATION ENGINEERING',
    'AUT': 'AUTOMOBILE ENGINEERING',
    'AIM': 'ARTIFICIAL INTELLIGENCE AND MACHINE LEARNING',
    'MIN': 'MINING ENGINEERING',
    'ANE': 'AERONAUTICAL ENGINEERING',
    'BIO': 'BIO-MEDICAL ENGINEERING',
    'CIC': 'CSE (IOT AND CYBER SECURITY INCLUDING BLOCK CHAIN TECHNOLOGY)',
    'EEC': 'ELECTRONICS ENGINEERING (VLSI DESIGN AND TECHNOLOGY)',
    'AI': 'ARTIFICIAL INTELLIGENCE',
    'CSN': 'COMPUTER SCIENCE AND ENGINEERING (NETWORKS)',
    'CE': 'COMPUTER ENGINEERING',
    'CHE': 'CHEMICAL ENGINEERING',
    'MMT': 'METALLURGICAL ENGINEERING',
    'MTM': 'METALLURGY AND MATERIAL ENGINEERING',
    'MFG': 'BTECH MECHANICAL WITH MTECH MANUFACTURING SYSTEMS',
    'THT': 'BTECH MECHANICAL WITH MTECH THERMAL ENGG',
    'MTR': 'MECHANICAL (MECHATRONICS) ENGINEERING',
    'GEO': 'GEO INFORMATICS',
    'ECI': 'ELECTRONICS COMMUNICATION AND INSTRUMENTATION ENGINEERING',
    'ECM': 'ELECTRONICS AND COMPUTER ENGINEERING',
    'AGR': 'AGRICULTURAL ENGINEERING',
    'FT': 'FOOD TECHNOLOGY',
    'PHM': 'PHARMACEUTICAL ENGINEERING',
    'CSA': 'COMPUTER SCIENCE AND ENGG (ARTIFICIAL INTELLIGENCE)',
    'DTP': 'DIGITAL TECHNIQUES FOR DESIGN AND PLANNING',
    'CSI': 'COMPUTER SCIENCE AND INFORMATION TECHNOLOGY',
    'DRY': 'DAIRYING',
    'TXT': 'TEXTILE TECHNOLOGY / TEXTILE ENGINEERING',
    'CSDN': 'COMPUTER SCIENCE & DESIGN',
    'BT': 'BIO-TECHNOLOGY',
    'BPL': 'B.PLANNING',
    'BSE': 'BUILDING SERVICES ENGINEERING',
    'ETM': 'ELECTRONICS AND TELEMATICS'
}

# Phase to file path mapping
PHASE_FILES = {
    "Final Phase": "./data/03_TGEAPCET_2024_FinalPhase.csv",
    "1st Phase": "./data/01_TGEAPCET_2024_FirstPhase.csv",
    "2nd Phase": "./data/02_TGEAPCET_2024_SecondPhase.csv"
}

# Caste mapping for column names


def get_caste_column_name(gender, caste):
    """
    Get the caste column name based on caste and gender.

    Args:
        caste (str): The caste category (OC, BC_A, etc.)
        gender (str): The gender (Male or Female)

    Returns:
        str: The column name in the dataset
    """
    caste_map = {
        'OC': 'OC',
        'BC_A': 'BC_A',
        'BC_B': 'BC_B',
        'BC_C': 'BC_C',
        'BC_D': 'BC_D',
        'BC_E': 'BC_E',
        'SC': 'SC',
        'ST': 'ST',
        'EWS': 'EWS GEN OU' if gender == 'Male' else 'EWS GIRLS OU'
    }

    if caste == 'EWS':
        return caste_map[caste]
    else:
        gender_suffix = 'BOYS' if gender == 'Male' else 'GIRLS'
        return f"{caste_map[caste]} {gender_suffix}"


# List of top colleges (reordered)
TOP_COLLEGES = [
    {"name": "JNTUH UNIVERSITY COLLEGE OF ENGG SCI AND TECH HYDERABAD",
        "details": "Premier government engineering college under JNTUH, known for strong academics and placements"},
    {"name": "CHAITANYA BHARATHI INSTITUTE OF TECHNOLOGY",
        "details": "Highly reputed autonomous institute with strong industry connections and placements"},
    {"name": "V N R VIGNANA JYOTHI INSTITUTE OF ENGG AND TECH",
        "details": "Strong academics and good infrastructure with consistent placement records"},
    {"name": "VASAVI COLLEGE OF ENGINEERING",
        "details": "Renowned for quality education, disciplined environment, and good placements"},
    {"name": "GOKARAJU RANGARAJU INSTITUTE OF ENGG AND TECH",
        "details": "Autonomous institute with excellent infrastructure and placements"},
    {"name": "KESHAV MEMORIAL INST OF TECHNOLOGY",
        "details": "Known for CSE and IT programs with good placement record"},
    {"name": "O U COLLEGE OF ENGG HYDERABAD",
        "details": "Oldest and prestigious engineering college in Telangana under OU"},
    {"name": "NEIL GOGTE INST OF TECHNOLOGY",
        "details": "Emerging college with focus on innovation and new-age tech programs"},
    {"name": "SRINIDHI INSTITUTE OF SCI AND TECHNOLOGY",
        "details": "Popular autonomous institute with good placements and strong faculty"},
    {"name": "MAHATMA GANDHI INSTITUTE OF TECHNOLOGY (AUTONOMOUS)",
     "details": "Autonomous institute with good focus on engineering education and placements"},
    {"name": "CVR COLLEGE OF ENGINEERING",
        "details": "Top-ranked private college known for discipline, placements and academics"},
    {"name": "GEETANJALI COLLEGE OF ENGG AND TECHNOLOGY (AUTONOMOUS)",
        "details": "Autonomous engineering college with modern infrastructure and industry-oriented programs"},
    {"name": "GURUNANAK INST OF TECHNOLOGY (AUTONOMOUS)",
        "details": "Autonomous institute known for quality technical education and placement opportunities"},
    {"name": "INSTITUTE OF AERONAUTICAL ENGINEERING",
        "details": "Well-known for aeronautics, CSE and ECE with good placement opportunities"},
    {"name": "B V RAJU INSTITUTE OF TECHNOLOGY",
        "details": "Well-established college in Narsapur known for its campus and academics"},
    {"name": "ANURAG UNIVERSITY (FORMERLY ANURAG GRP OF INSTNS- CVSR COLL OF ENGG)",
     "details": "Now a private university with good infrastructure and course variety"},
    {"name": "VARDHAMAN COLLEGE OF ENGINEERING",
        "details": "Autonomous college with good academics and modern infrastructure"},
    {"name": "C M R COLLEGE OF ENGG AND TECHNOLOGY (AUTONOMOUS)",
        "details": "Autonomous engineering college with focus on technical excellence and industry partnerships"},
    {"name": "M V S R ENGINEERING COLLEGE (AUTONOMOUS)",
     "details": "Established autonomous college with consistent placement track record"},
    {"name": "K U COLLEGE OF ENGG KOTHAGUDEM",
        "details": "Constituent college of Kakatiya University with good academic reputation"}
]

TOP_COLLEGES_CUTTOFF_MALES = [
    {"name": "JNTUH UNIVERSITY COLLEGE OF ENGG SCI AND TECH HYDERABAD",
        "details": "Premier government engineering college under JNTUH, known for strong academics and placements"},
    {"name": "V N R VIGNANA JYOTHI INSTITUTE OF ENGG AND TECH",
        "details": "Strong academics and good infrastructure with consistent placement records"},
    {"name": "CHAITANYA BHARATHI INSTITUTE OF TECHNOLOGY",
        "details": "Highly reputed autonomous institute with strong industry connections and placements"},
    {"name": "VASAVI COLLEGE OF ENGINEERING",
        "details": "Renowned for quality education, disciplined environment, and good placements"},
    {"name": "O U COLLEGE OF ENGG  HYDERABAD",
        "details": "Oldest and prestigious engineering college in Telangana under OU"},
    {"name": "GOKARAJU RANGARAJU INSTITUTE OF ENGG AND TECH",
        "details": "Autonomous institute with excellent infrastructure and placements"},
    {"name": "KESHAV MEMORIAL INST OF TECHNOLOGY",
        "details": "Known for CSE and IT programs with good placement record"},
    {"name": "JNTUH UNIVERSITY COLLEGE OF ENGG SCI AND TECH  -5 YEAR INTEGRATED MTECH  SELF FINANCE",
        "details": "Integrated MTech program under JNTUH with self-finance model"},
    {"name": "CVR COLLEGE OF ENGINEERING",
        "details": "Top-ranked private college known for discipline, placements and academics"},
    {"name": "MAHATMA GANDHI INSTITUTE OF TECHNOLOGY (AUTONOMOUS)",
     "details": "Autonomous institute with good focus on engineering education and placements"},
    {"name": "K U COLLEGE OF ENGG  KOTHAGUDEM",
        "details": "Constituent college of Kakatiya University with good academic reputation"},
    {"name": "VARDHAMAN COLLEGE OF ENGINEERING",
        "details": "Autonomous college with good academics and modern infrastructure"},
    {"name": "B V RAJU INSTITUTE OF TECHNOLOGY",
        "details": "Well-established college in Narsapur known for its campus and academics"},
    {"name": "M V S R ENGINEERING COLLEGE (AUTONOMOUS)",
     "details": "Established autonomous college with consistent placement track record"},
    {"name": "SRINIDHI INSTITUTE OF SCI AND TECHNOLOGY",
        "details": "Popular autonomous institute with good placements and strong faculty"},
    {"name": "JNTUH UNIVERSITY COLLEGE OF ENGINEERING  SULTANPUR",
        "details": "Government college under JNTUH with developing infrastructure and growing reputation"},
    {"name": "NEIL GOGTE INST OF TECHNOLOGY",
        "details": "Emerging college with focus on innovation and new-age tech programs"},
    {"name": "ANURAG UNIVERSITY (FORMERLY ANURAG GRP OF INSTNS- CVSR COLL OF ENGG)",
     "details": "Now a private university with good infrastructure and course variety"},
    {"name": "INSTITUTE OF AERONAUTICAL ENGINEERING",
        "details": "Well-known for aeronautics, CSE and ECE with good placement opportunities"},
    {"name": "JNTUH UNIVERSITY COLLEGE OF ENGINEERING  JAGITIAL (AUTONOMOUS)",
     "details": "JNTUH constituent autonomous college with improving facilities and academics"}
]


TOP_COLLEGES_CUTTOFF_FEMALES = [
    {"name": "JNTUH UNIVERSITY COLLEGE OF ENGG SCI AND TECH HYDERABAD",
     "details": "Top-tier government engineering institute under JNTUH, known for academic excellence"},
    {"name": "V N R VIGNANA JYOTHI INSTITUTE OF ENGG AND TECH",
     "details": "Leading private institute with strong placements and industry-oriented curriculum"},
    {"name": "CHAITANYA BHARATHI INSTITUTE OF TECHNOLOGY",
     "details": "Highly reputed institute offering diverse programs and excellent placement opportunities"},
    {"name": "VASAVI COLLEGE OF ENGINEERING",
     "details": "Autonomous institute offering high-quality education with consistent results"},
    {"name": "O U COLLEGE OF ENGG  HYDERABAD",
     "details": "Historical government engineering college under OU, known for its legacy"},
    {"name": "GOKARAJU RANGARAJU INSTITUTE OF ENGG AND TECH",
     "details": "Top-ranked private college with excellent academics and infrastructure"},
    {"name": "G NARAYNAMMA INSTITUTE OF TECHNOLOGY AND SCI",
     "details": "Premier women’s engineering college with great placements and safe campus"},
    {"name": "KESHAV MEMORIAL INST OF TECHNOLOGY",
     "details": "Well-known for IT and CSE branches with strong academic and placement record"},
    {"name": "CVR COLLEGE OF ENGINEERING",
     "details": "Well-disciplined private college with a strong emphasis on placements and academics"},
    {"name": "JNTUH UNIVERSITY COLLEGE OF ENGG SCI AND TECH  -5 YEAR INTEGRATED MTECH  SELF FINANCE",
     "details": "Integrated MTech self-financed program offered by JNTUH"},
    {"name": "B V RAJU INSTITUTE OF TECHNOLOGY",
     "details": "Autonomous institute with modern facilities and consistent placement performance"},
    {"name": "MAHATMA GANDHI INSTITUTE OF TECHNOLOGY (AUTONOMOUS)",
     "details": "Good academic track with autonomous status and quality faculty"},
    {"name": "M V S R ENGINEERING COLLEGE (AUTONOMOUS)",
     "details": "Autonomous college offering a good academic environment and placements"},
    {"name": "SRINIDHI INSTITUTE OF SCI AND TECHNOLOGY",
     "details": "Popular institute with strong faculty and placement records"},
    {"name": "VARDHAMAN COLLEGE OF ENGINEERING",
     "details": "Well-maintained campus with growing reputation in academics and placements"},
    {"name": "BVRIT COLLEGE OF ENGINEERING FOR WOMEN (AUTONOMOUS)",
     "details": "Dedicated women’s engineering college with growing opportunities and placement support"},
    {"name": "NEIL GOGTE INST OF TECHNOLOGY",
     "details": "Emerging institute with modern tech courses and focus on innovation"},
    {"name": "JNTUH UNIVERSITY COLLEGE OF ENGINEERING  SULTANPUR",
     "details": "Government college under JNTUH with expanding facilities and reputation"},
    {"name": "JNTUH UNIVERSITY COLLEGE OF ENGINEERING  JAGITIAL (AUTONOMOUS)",
     "details": "Autonomous government college offering quality education under JNTUH"},
    {"name": "ANURAG UNIVERSITY (FORMERLY ANURAG GRP OF INSTNS- CVSR COLL OF ENGG)",
     "details": "Private university offering wide range of programs and modern infrastructure"}
]


TOP_COLLEGES__FEMALES = [
    {"name": "JNTUH UNIVERSITY COLLEGE OF ENGG SCI AND TECH HYDERABAD",
     "details": "Premier government engineering college under JNTUH, known for strong academics and placements"},
    {"name": "CHAITANYA BHARATHI INSTITUTE OF TECHNOLOGY",
        "details": "Highly reputed autonomous institute with strong industry connections and placements"},
    {"name": "V N R VIGNANA JYOTHI INSTITUTE OF ENGG AND TECH",
        "details": "Strong academics and good infrastructure with consistent placement records"},
    {"name": "VASAVI COLLEGE OF ENGINEERING",
        "details": "Renowned for quality education, disciplined environment, and good placements"},
    {"name": "GOKARAJU RANGARAJU INSTITUTE OF ENGG AND TECH",
        "details": "Autonomous institute with excellent infrastructure and placements"},
    {"name": "G NARAYNAMMA INSTITUTE OF TECHNOLOGY AND SCI",
        "details": "Premier women’s engineering college with great placements and safe campus"},
    {"name": "KESHAV MEMORIAL INST OF TECHNOLOGY",
        "details": "Known for CSE and IT programs with good placement record"},
    {"name": "O U COLLEGE OF ENGG HYDERABAD",
        "details": "Oldest and prestigious engineering college in Telangana under OU"},
    {"name": "NEIL GOGTE INST OF TECHNOLOGY",
        "details": "Emerging college with focus on innovation and new-age tech programs"},
    {"name": "BHOJREDDY ENGINEERING COLLEGE FOR WOMEN",
        "details": "Reputed women’s college focused on technical education and women empowerment"},
    {"name": "SRINIDHI INSTITUTE OF SCI AND TECHNOLOGY",
        "details": "Popular autonomous institute with good placements and strong faculty"},
    {"name": "MAHATMA GANDHI INSTITUTE OF TECHNOLOGY (AUTONOMOUS)",
        "details": "Autonomous institute with good focus on engineering education and placements"},
    {"name": "CVR COLLEGE OF ENGINEERING",
        "details": "Top-ranked private college known for discipline, placements and academics"},
    {"name": "GEETANJALI COLLEGE OF ENGG AND TECHNOLOGY (AUTONOMOUS)",
        "details": "Autonomous engineering college with modern infrastructure and industry-oriented programs"},
    {"name": "GURUNANAK INST OF TECHNOLOGY (AUTONOMOUS)",
        "details": "Autonomous institute known for quality technical education and placement opportunities"},
    {"name": "INSTITUTE OF AERONAUTICAL ENGINEERING",
        "details": "Well-known for aeronautics, CSE and ECE with good placement opportunities"},
    {"name": "B V RAJU INSTITUTE OF TECHNOLOGY",
        "details": "Well-established college in Narsapur known for its campus and academics"},
    {"name": "ANURAG UNIVERSITY (FORMERLY ANURAG GRP OF INSTNS- CVSR COLL OF ENGG)",
        "details": "Now a private university with good infrastructure and course variety"},
    {"name": "VARDHAMAN COLLEGE OF ENGINEERING",
        "details": "Autonomous college with good academics and modern infrastructure"},
    {"name": "C M R COLLEGE OF ENGG AND TECHNOLOGY (AUTONOMOUS)",
        "details": "Autonomous engineering college with focus on technical excellence and industry partnerships"},
]


TOP_COLLEGES__MALES = [
    {"name": "JNTUH UNIVERSITY COLLEGE OF ENGG SCI AND TECH HYDERABAD",
        "details": "Premier government engineering college under JNTUH, known for strong academics and placements"},
    {"name": "CHAITANYA BHARATHI INSTITUTE OF TECHNOLOGY",
        "details": "Highly reputed autonomous institute with strong industry connections and placements"},
    {"name": "V N R VIGNANA JYOTHI INSTITUTE OF ENGG AND TECH",
        "details": "Strong academics and good infrastructure with consistent placement records"},
    {"name": "VASAVI COLLEGE OF ENGINEERING",
        "details": "Renowned for quality education, disciplined environment, and good placements"},
    {"name": "GOKARAJU RANGARAJU INSTITUTE OF ENGG AND TECH",
        "details": "Autonomous institute with excellent infrastructure and placements"},
    {"name": "KESHAV MEMORIAL INST OF TECHNOLOGY",
        "details": "Known for CSE and IT programs with good placement record"},
    {"name": "O U COLLEGE OF ENGG HYDERABAD",
        "details": "Oldest and prestigious engineering college in Telangana under OU"},
    {"name": "NEIL GOGTE INST OF TECHNOLOGY",
        "details": "Emerging college with focus on innovation and new-age tech programs"},
    {"name": "SRINIDHI INSTITUTE OF SCI AND TECHNOLOGY",
        "details": "Popular autonomous institute with good placements and strong faculty"},
    {"name": "MAHATMA GANDHI INSTITUTE OF TECHNOLOGY (AUTONOMOUS)",
     "details": "Autonomous institute with good focus on engineering education and placements"},
    {"name": "CVR COLLEGE OF ENGINEERING",
        "details": "Top-ranked private college known for discipline, placements and academics"},
    {"name": "GEETANJALI COLLEGE OF ENGG AND TECHNOLOGY (AUTONOMOUS)",
        "details": "Autonomous engineering college with modern infrastructure and industry-oriented programs"},
    {"name": "GURUNANAK INST OF TECHNOLOGY (AUTONOMOUS)",
        "details": "Autonomous institute known for quality technical education and placement opportunities"},
    {"name": "INSTITUTE OF AERONAUTICAL ENGINEERING",
        "details": "Well-known for aeronautics, CSE and ECE with good placement opportunities"},
    {"name": "B V RAJU INSTITUTE OF TECHNOLOGY",
        "details": "Well-established college in Narsapur known for its campus and academics"},
    {"name": "ANURAG UNIVERSITY (FORMERLY ANURAG GRP OF INSTNS- CVSR COLL OF ENGG)",
     "details": "Now a private university with good infrastructure and course variety"},
    {"name": "VARDHAMAN COLLEGE OF ENGINEERING",
        "details": "Autonomous college with good academics and modern infrastructure"},
    {"name": "C M R COLLEGE OF ENGG AND TECHNOLOGY (AUTONOMOUS)",
        "details": "Autonomous engineering college with focus on technical excellence and industry partnerships"},
    {"name": "M V S R ENGINEERING COLLEGE (AUTONOMOUS)",
     "details": "Established autonomous college with consistent placement track record"},
    {"name": "K U COLLEGE OF ENGG KOTHAGUDEM",
        "details": "Constituent college of Kakatiya University with good academic reputation"}
]
